spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  messages:
    basename: messages
    cache-duration: -1
    encoding: UTF-8
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  profiles:
    active: local
server:
  port: 8081
log:
  level: INFO