spring:
  datasource:
    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #    url: jdbc:h2:file:./target/db/testdb
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
log:
  level: DEBUG