spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  messages:
    basename: messages
    cache-duration: -1
    encoding: UTF-8
server:
  port: 8081
log:
  level: INFO