name: Review
on: [pull_request]

jobs:
  build:
   name: Danger JS
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v1
     - name: Danger
       uses: danger/danger-js@9.1.6
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# on: 
#   pull_request:
#     branches:
#       - master
#       - release/*

# jobs:
#   danger:

#     runs-on: ubuntu-latest
#     steps:
#       - name: setup Node.js
#         uses: actions/setup-node@v1
#       - name: install yarn
#         run: npm install -g yarn
#       - name: install danger
#         run: yarn add danger --dev
#       - name: run danger
#         run: danger

# # yarn install
# #     - name: Danger JS Action
# #       uses: danger/danger-js@9.2.10
# #       env:
# #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
