name: Review
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Build with Maven for ktlint
      run: mvn -B package --file pom.xml
    - name: ktlint
      run: mvn antrun:run@ktlint
    - name: Upload lint artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: lint-artifact
        path: ./target/ktlint.json
        
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Generate coverage report
      run: mvn test
    - name: Upload test artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: test-artifact
        path: ./target/site

  danger:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Download lint artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: lint-artifact
        path: ./target/ktlint.json
    - name: setup Node.js
      uses: actions/setup-node@v1
      if: always()
    - name: install yarn
      run: npm install -g yarn
      if: always()
    - name: install danger
      run: |
        yarn add danger --dev
      if: always()
    - name: Danger
      run: yarn danger ci
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: always()

  codecov:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Download test artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: test-artifact
        path: ./target/site
    - name: upload to codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
        file: ./target/site/jacoco/jacoco.xml
