name: Review
on: [pull_request]

jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Build with Maven for ktlint
        run: mvn -B package --file pom.xml
      - name: ktlint
        run: mvn antrun:run@ktlint
        if: always()
      - name: ls
        run: ls -l
      - name: setup Node.js
        uses: actions/setup-node@v1
      - name: install yarn
        run: npm install -g yarn
      - name: install danger
        run: yarn add danger --dev
      - name: Danger
        run: yarn danger ci
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
